version: '3'

services:
  app:
    # Build dockerfile
    build: .
    # Restart container in case of crashes etc
    restart: always
    # Set API to use host networking
    network_mode: host
    # API depends on DB to be there
    # depends_on:
    #   - db
    # Set env variables
    environment:
      APP_KEY: jlG45rVkU1PSx7DBngfjQ3RfozrY_kk0
      SESSION_DRIVER: cookie
      DB_CONNECTION: mssql
      MSSQL_SERVER: ${MSSQL_SERVER}
      MSSQL_PORT: 1433
      MSSQL_USER: ${MSSQL_USER}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_DB_NAME: smartgaragedb
      MAILGUN_API_KEY: f1d8330f6ccb108590bc6f7dd33149af-523596d9-57e268a4
      MAILGUN_DOMAIN: sandbox5dd856b1368a41999ce79469d7a5b481.mailgun.org
  web:
    image: nginx
    container_name: nginx
    ports:
     - "80:80"
    volumes:
     - ./nginx/:/etc/nginx/conf.d/

#   db:
#     # Set DB version to run
#     image: postgres:13.3-alpine
#     # Restart container in case of crashes etc
#     restart: always
#     # Set DB to use host networking
#     network_mode: host
#     # Set DB env variables
#     environment:
#       POSTGRES_PASSWORD: example
#     # Mount DB data to volume, 
#     # so we don't lose all DB data over deployments
#     volumes:
#       - database:/var/lib/postgresql/data

# # Define the DB volume
# volumes:
#   database:
